### ISSUE TITLE
deselectAll error

### ISSUE THREAD

**Issue by richardshergold** [briebug/ngrx-auto-entity#62] opened 2019-09-04 08:55 UTC
I'm doing an updateMany call in my facade on a bunch of selected items which works fine but when I follow this up with a call to deslelectAll() in order to deselect the items that I updated, I get an error:

```
ERROR TypeError: Cannot read property 'map' of undefined
    at briebug-ngrx-auto-entity.js:1570
    at store.js:576
    at memoized (store.js:526)
    at defaultStateFn (store.js:545)
    at store.js:579
    at memoized (store.js:526)
    at MapSubscriber.project (store.js:473)
```
Although the error occurs the items are actually de-selected in the state i.e the currentEntityKeys property disappears

Here's my facade method:

```
markRead() {
    this.currentSet$.pipe(take(1)).subscribe((items: any[]) => {
      this.updateMany(items, {
        flagType: "read",
        flagValue: !items[0].read 
      });
      this.deselectAll();   // ERROR OCCURS HERE
    });
  }
```

if I move the deslectAll outside of my currentSet subscription it works i.e 

```
markRead() {
    this.currentSet$.pipe(take(1)).subscribe((items: any[]) => {
      this.updateMany(items, {
        flagType: "read",
        flagValue: !items[0].read
      });
    });
    this.deselectAll(); // THIS WORKS
  }
```

Should the first method work?

**Comment by jrista** [comment] 2019-09-04 16:24
I would think the first method should work, and seems it would be the more correct implementation. I'll look into this, as I wonder if there may be some kind of timing issue.

**Comment by jrista** [comment] 2019-09-05 16:21
@richardshergold Any chance you could create a small project to reproduce this issue?

**Comment by jrista** [comment] 2019-09-06 01:16
I believe I have identified the causes of this bug. I was making some invalid assumptions in the reducer, that certain data would always be arrays when in fact sometimes they could be falsy. I've added the necessary checks to ensure that the code functions even in the presence of falsy values. 

I will also be adding some additional checks to some of the actions, to ensure that certain arguments meet certain requirements, such as if an argument is expected to be an array, it is, or if it is expected to be an object, it is. These checks will throw if the expectations are not met. For now, I am going to allow these exceptions to bubble up, and not bother catching them in any of the generated facade code, so it will be up to the caller to handle them appropriately (either that, or just make sure you never pass in the wrong kind of data. ;))

**Comment by richardshergold** [comment] 2019-09-06 07:30
@jrista FYI - after upgrading to 0.2.6 my second method stopped working - there was an error on the deselectAll call which worked in 0.2.5.  However, by reverting back to the first method **AND** changing the call to deselectMany instead of deSelectAll it now works i.e to toggle an item on and off this code now works:

```
markRead() {
    this.currentSet$.pipe(take(1)).subscribe((items: any[]) => {
      this.updateMany(items, {
        flagType: "read",
        flagValue: !items[0].read
      });
      this.deselectMany(items);  
    });
  }
```

**Comment by jrista** [comment] 2019-09-09 20:02
Hmm, it is strange that `deselectAll()` is not working. I think I'll need a working replication of the issue to resolve the issue there. 

Is it just not deselecting anything? Or are you getting an error? Or, are you seeing an error in the log?

**Comment by jrista** [comment] 2019-10-14 18:42
@richardshergold Are you still getting errors when using `deselectAll()`? If so, could you share one of the error logs here?

**Comment by richardshergold** [comment] 2019-10-14 18:52
Sorry. Project is now on back burner so have not looked at this for a while. Feel free to close. I will let you know when I’m back on it!

**Comment by jrista** [comment] 2019-10-14 19:40
I'll keep this open. Whenever you get a chance. Thanks for the update.

**Comment by jrista** [comment] 2020-04-18 03:24
@richardshergold We may have resolved the underlying bug that was causing this. We had some issues internal to the reducer and selectors in the past that were leading to some undefined errors. Could you try upgrading to auto-entity 0.4.x or maybe 0.5.x alpha, and see if the error persists?

**Comment by jrista** [comment] 2020-08-03 19:30
I believe this issue was resolved with the redesign of our selectors. Undefined errors should no longer occur with the selectors now check for the existence of the required properties before returning.

**Closed by jrista** 2020-08-03 19:30 UTC
Labels: bug, question
